project("app")
	location(g_wkslight.workspacedir .. "/%{prj.name}")
	targetdir(g_wkslight.targetdir)
	debugdir("")
	debugargs({ "" })
	kind("ConsoleApp")
	language("C++")
	files({
		"src/**.h",
		"src/**.cpp",
	})
	includedirs({
		"src",
	})
	g_wkslight.uselibs({
		"bar",
		"foo",
		"headeronly",
		"linmath",
	})
	filter("options:android")
		androidprojectdependencies({
			"bar",
			"foo",
		})
	filter("options:uwp")
		files({
			"Package.appxmanifest",
		})
	filter("platforms:wasm")
		g_wkslight.wasmlinkoptions(g_wkslight.extras.wasm)