#!/usr/bin/env python3

import sys
from http.server import HTTPServer, SimpleHTTPRequestHandler

class HTTPRequestHandler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=sys.argv[1], **kwargs)

    def end_headers(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cross-Origin-Embedder-Policy", "require-corp")
        self.send_header("Cross-Origin-Opener-Policy", "same-origin")
        super().end_headers()

def main(addr, port):
    with HTTPServer((addr, port), HTTPRequestHandler) as httpd:
        print(f"serving at http://{addr}:{port}")
        
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("bye!")

if __name__ == "__main__":
    main("0.0.0.0", 8000)