@echo off
setlocal enabledelayedexpansion

cd ..

set SDL3_NAME=SDL3
set SDL3_IMAGE_NAME=SDL3_image
set SDL3_MIXER_NAME=SDL3_mixer
set SDL3_NET_NAME=SDL3_net
set SDL3_TTF_NAME=SDL3_ttf

set SDL3_DIST_VERSION=3.2.14
set SDL3_IMAGE_DIST_VERSION=3.2.4
set SDL3_MIXER_DIST_VERSION=2.8.1
set SDL3_NET_DIST_VERSION=2.2.0
set SDL3_TTF_DIST_VERSION=3.2.2

set SDL3_DEV=devel
set SDL3_ARCH=x64
set SDL3_DIST_SUFFIX=VC.zip

set SDL3_DIST_FILENAME=%SDL3_NAME%-%SDL3_DEV%-%SDL3_DIST_VERSION%-%SDL3_DIST_SUFFIX%
set SDL3_IMAGE_DIST_FILENAME=%SDL3_IMAGE_NAME%-%SDL3_DEV%-%SDL3_IMAGE_DIST_VERSION%-%SDL3_DIST_SUFFIX%
set SDL3_MIXER_DIST_FILENAME=%SDL3_MIXER_NAME%-%SDL3_DEV%-%SDL3_MIXER_DIST_VERSION%-%SDL3_DIST_SUFFIX%
set SDL3_NET_DIST_FILENAME=%SDL3_NET_NAME%-%SDL3_DEV%-%SDL3_NET_DIST_VERSION%-%SDL3_DIST_SUFFIX%
set SDL3_TTF_DIST_FILENAME=%SDL3_TTF_NAME%-%SDL3_DEV%-%SDL3_TTF_DIST_VERSION%-%SDL3_DIST_SUFFIX%

set SDL3_DIST_URL_PART1_ARR[0]=SDL
set SDL3_DIST_URL_PART1_ARR[1]=SDL_image
set SDL3_DIST_URL_PART1_ARR[2]=SDL_mixer
set SDL3_DIST_URL_PART1_ARR[3]=SDL_net
set SDL3_DIST_URL_PART1_ARR[4]=SDL_ttf

set SDL3_DIST_URL_PART2_ARR[0]=%SDL3_DIST_VERSION%
set SDL3_DIST_URL_PART2_ARR[1]=%SDL3_IMAGE_DIST_VERSION%
set SDL3_DIST_URL_PART2_ARR[2]=%SDL3_MIXER_DIST_VERSION%
set SDL3_DIST_URL_PART2_ARR[3]=%SDL3_NET_DIST_VERSION%
set SDL3_DIST_URL_PART2_ARR[4]=%SDL3_TTF_DIST_VERSION%

set SDL3_DIST_URL_PART3_ARR[0]=%SDL3_DIST_FILENAME%
set SDL3_DIST_URL_PART3_ARR[1]=%SDL3_IMAGE_DIST_FILENAME%
set SDL3_DIST_URL_PART3_ARR[2]=%SDL3_MIXER_DIST_FILENAME%
set SDL3_DIST_URL_PART3_ARR[3]=%SDL3_NET_DIST_FILENAME%
set SDL3_DIST_URL_PART3_ARR[4]=%SDL3_TTF_DIST_FILENAME%

set SDL3_DIST_DIRNAME_ARR[0]=%SDL3_NAME%-%SDL3_DIST_VERSION%
set SDL3_DIST_DIRNAME_ARR[1]=%SDL3_IMAGE_NAME%-%SDL3_IMAGE_DIST_VERSION%
set SDL3_DIST_DIRNAME_ARR[2]=%SDL3_MIXER_NAME%-%SDL3_MIXER_DIST_VERSION%
set SDL3_DIST_DIRNAME_ARR[3]=%SDL3_NET_NAME%-%SDL3_NET_DIST_VERSION%
set SDL3_DIST_DIRNAME_ARR[4]=%SDL3_TTF_NAME%-%SDL3_TTF_DIST_VERSION%

set /a SDL3_DIST_LEN=5
set /a SDL3_DIST_LAST=%SDL3_DIST_LEN%-1
set /a SDL3_DIST_FILELIST_ALL_EXIST=1

set "SDL3_DIST_FILELIST="
for /L %%i in (0,1,%SDL3_DIST_LEN%) do (
    set "SDL3_DIST_FILELIST=!SDL3_DIST_FILELIST! !SDL3_DIST_URL_PART3_ARR[%%i]!"
)
set "SDL3_DIST_FILELIST=%SDL3_DIST_FILELIST:~1,-1%"

set OPT_DIRNAME=opt
set OPT_TEMP_DIRNAME=temp
set BINARY_DIR=../bin/target/%SDL3_ARCH%/Release

mkdir %OPT_DIRNAME%
pushd %OPT_DIRNAME%

for %%i in (%SDL3_DIST_FILELIST%) do (
    if not exist %%i (
        set /a SDL3_DIST_FILELIST_ALL_EXIST=0
        goto BREAK1
    )
)

:BREAK1
echo SDL3_DIST_FILELIST_ALL_EXIST=!SDL3_DIST_FILELIST_ALL_EXIST!

if %SDL3_DIST_FILELIST_ALL_EXIST% equ 0 (
    for /L %%i in (0,1,%SDL3_DIST_LAST%) do (
        curl -LO "https://github.com/libsdl-org/!SDL3_DIST_URL_PART1_ARR[%%i]!/releases/download/release-!SDL3_DIST_URL_PART2_ARR[%%i]!/!SDL3_DIST_URL_PART3_ARR[%%i]!"
    )
)

if not exist %OPT_TEMP_DIRNAME% (
    mkdir %OPT_TEMP_DIRNAME%
    
    for /L %%i in (0,1,%SDL3_DIST_LAST%) do (
        powershell -Command "Expand-Archive -Force -LiteralPath !SDL3_DIST_URL_PART3_ARR[%%i]! -DestinationPath %OPT_TEMP_DIRNAME%"
    )
)

for /L %%i in (0,1,%SDL3_DIST_LAST%) do (
    xcopy /I /Y "%OPT_TEMP_DIRNAME%\!SDL3_DIST_DIRNAME_ARR[%%i]!\lib\%SDL3_ARCH%\*.dll" "%BINARY_DIR%"
)

popd