#!/usr/bin/env python3
from http.server import HTTPServer, SimpleHTTPRequestHandler

class HTTPRequestHandler(SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cross-Origin-Embedder-Policy", "require-corp")
        self.send_header("Cross-Origin-Opener-Policy", "same-origin")
        super().end_headers()

def main(addr, port):
    with HTTPServer((addr, port), HTTPRequestHandler) as httpd:
        print(f"serving at http://{addr}:{port}")
        
        try:
            httpd.serve_foreve()
        except KeyboardInterrupt:
            print("bye!")

if __name__ == "__main__:
    main("", 8000)