name: CI

on:
  pull_request:
    branches: [ "main", "master" ]
    
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup premake5
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta2"

      # Windows
      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: "latest"
      - name: Build app for release
        if: runner.os == 'Windows'
        run: |
          premake5 vs2022
          msbuild build\wkslight.sln -nologo -m -p:Configuration=Release -p:Platform=x64 -p:Projects="build\app\app.vcxproj"
      
      # Linux & macOS
      - name: Build
        if: runner.os != 'Windows'
        run: |
          premake5 gmake2
          pushd build
          make config=release_x64
          popd
        
      - name: Create artifact
        run: |
          mkdir -p temp/artifact
          cp -r bin/x64/Release temp/artifact/
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Release-Artifact-${{ runner.os }}
          path: temp
