name: CI android

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup premake5
        uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta5"

      - name: Setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.5.1

      - name: Build
        run: |
          java --version
          gradle -V
          source scripts/tool-keygen.sh
          source scripts/tool-premake5+x.sh ${{ github.workspace }}

          ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME
          source scripts/11-premake5-generate-android.sh
          source scripts/android-buildw.sh

      - name: Create artifact
        run: |
          mkdir -p temp/artifact/android
          cp -rv bin/* temp/artifact/android

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release-Artifact-android
          path: ${{ github.workspace }}/temp
