name: CI Android

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup premake5
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta2"

      - name: Setup jdk
        uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '17'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.5.1

      - name: Build
        run: |
          java --version

          mkdir $HOME/.android
          keytool -genkey -v -keystore $HOME/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"

          ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME

          source premake5-generate-android.sh
          source android-build.sh

      - name: Create artifact
        run: |
          mkdir -p "temp/artifact/android/"
          cp -r bin/* "temp/artifact/android/"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Release-Artifact-android
          path: temp
