name: CI Android

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup premake5
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta2"

      - name: Install Dependencies
        run: |
          echo "hello"

      - name: Build
        run: |
          ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME

          source premake5-generate-android.sh
          source android-build.sh

      - name: Create artifact
        run: |
          mkdir -p "temp/artifact/android/"
          cp -r bin/* "temp/artifact/android/"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Release-Artifact-android
          path: temp
