name: CI uwp

on:    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup premake5
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta2"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: "latest"

      - name: Build
        shell: cmd
        run: |
          scripts\premake5-generate-windows-uwp.bat
          "scripts\msbuild-windows-uwp.bat"
          "scripts/tool-run-pc.bat"

      - name: Create artifact
        run: |
          mkdir -p temp/artifact/${{ runner.os }}-uwp
          cp -r bin/* temp/artifact/${{ runner.os }}-uwp

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Release-Artifact-${{ runner.os }}-uwp
          path: temp