name: CI Web

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup premake5
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta2"

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14

      - name: Install Dependencies
        run: |
          emcc -v

          # This is just to trigger emsdk to compile ports
          echo -e '#include <SDL2/SDL.h>\nint main() { SDL_Init(SDL_INIT_VIDEO); SDL_Quit(); }' > main.c
          emcc main.c -O2 -sUSE_SDL=2 -sUSE_SDL_IMAGE=2 -sSDL2_IMAGE_FORMATS='["png"]' -sUSE_SDL_MIXER=2 -sUSE_SDL_NET=2 -sUSE_SDL_TTF=2 -o main.js

      - name: Build
        run: |
          source premake5-generate-web.sh

          pushd build
          make config=release_wasm
          popd
          
          rm -frv bin/wasm/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./bin
