name: CI Web

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup premake5
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta2"

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14

      - name: Build
        run: |
          emcc -v

          source premake5-generate-gmake.sh
          pushd build
          make config=release_wasm
          popd

          rm -frv bin/wasm/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./bin
