name: CI web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup premake5
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta2"

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14

      - name: Install Dependencies
        run: |
          emcc -v
          source scripts/tool-setup-dot-emscripten.sh
          source scripts/tool-emsdk-download-and-compile-ports.sh

      - name: Build
        run: |
          source scripts/14-premake5-generate-web.sh
          source scripts/24-gmake-web.sh
          source scripts/tool-web-post-build.sh

      - name: Create artifact
        run: |
          mkdir -p temp/artifact/web
          cp -rv bin/* temp/artifact/web

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Release-Artifact-web
          path: temp

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./bin/target
